server:
  port: 8001

spring:
  application:
    name: Twitter Test API
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TwitterTest
    username: root
    password: password
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: none
    show_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  flyway:
    baseline-on-migrate: true
    table: FlywayMigrationHistory
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    springfox.documentation.spring.web: INFO

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, threaddump, loggers, httptrace
  security:
    enabled: false